trigger:
- master

resources:
- repo: self

variables:
  containerRegistry: 'lakesideapp.azurecr.io'
  tag: '$(Build.BuildId)'

stages:
- stage: BuildAndPush
  displayName: Build and Push stage
  jobs:
  - job: Build
    displayName: Build
    steps:
    - script: |
        # Build and push individual Docker images for each service
        services=(customer-core customer-management-backend customer-management-frontend customer-self-service-backend customer-self-service-frontend)
        for service in "${services[@]}"; do
          docker compose build -t $(containerRegistry)/$service:$(tag) -f $service/Dockerfile .
          docker compose push $(containerRegistry)/$service:$(tag)
        done
      displayName: 'Build and push Docker images'
      env:
        DOCKER_BUILDKIT: '1'
        DOCKER_COMPOSE_DEBUG: 'true' # Enable debug logging
