trigger:
- master

resources:
- repo: self

variables:
  containerRegistry: 'lakesideapp.azurecr.io'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and push stage
  pool:
    name: MyPool
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: DockerCompose@0
      inputs:
        containerregistrytype: Azure Container Registry
        azureSubscription: Azure for Students(51fc861f-a84b-440f-bfd1-f4cf184c15d3)
        azureContainerRegistry: '{"loginServer":"lakesideapp.azurecr.io", "id" : "/subscriptions/51fc861f-a84b-440f-bfd1-f4cf184c15d3/resourceGroups/Lakeside/providers/Microsoft.ContainerRegistry/registries/LakesideApp"}'
        dockerComposeFile: 'docker-compose.yml'
        action: Run a Docker Compose command
        dockerComposeCommand: buildAndPush
      env:
        DOCKER_COMPOSE_DEBUG: 'true' # Enable debug logging